import Head from 'next/head';

export default function Home() {
  const tenis = [
    { id: 1, src: '1.png' },
    { id: 2, src: '2.png' },
    { id: 3, src: '3.png' },
    { id: 4, src: '4.png' },
    { id: 5, src: '5.png' },
    { id: 6, src: '6.png' },
    { id: 7, src: '7.png' },
    { id: 8, src: '8.png' },
  ];
  return (
    <>
      <Head>
        <title>Desafio 02 - Codelandia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <section className="bg-[#181818] flex min-h-[60px] place-items-center place-content-center">
          <p className="text-white text-center text-base">
            Ganhe R$ 10,00 de desconto no frete
          </p>
        </section>
        <section className="min-h-[60px] flex place-content-center place-items-center">
          <h1 className="text-center text-2xl">JordanShoes</h1>
        </section>
      </header>
      <main>
        <section className="bg-tenis h-[378px] w-full bg-cover bg-center">
          <div className="h-full w-full z-50 container m-auto relative px-5">
            <div className="container max-w-[1240px] h-full text-[#F9F9F9] flex place-items-center md:grid grid-cols-3 flex-row place-content-center">
              <div className="">
                <h1 className="text-[28px] md:text-[32px] font-bold pb-5">
                  A melhor loja de Jordan
                </h1>
                <h3 className="md:text-lg text-base">
                  O tênis Jordan é fruto de uma velha e forte parceria entre a
                  Nike e o jogador Michael Jordan.
                </h3>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="container m-auto max-w-[1240px]">
            <div className="flex place-content-center place-items-center flex-col">
              <h1 className="text-[28px] sm:text-[32px] font-semibold py-7">
                Destaques
              </h1>
              <h3 className="text-base sm:text-lg pb-16">
                Frete grátis e chinelo de brinde é aqui, aproveite por tempo
                limitado.{' '}
              </h3>
            </div>
            <div className="grid 2xl:grid-cols-4 md:grid-cols-3 xl:grid-cols-4 sm:grid-cols-2 grid-cols-1 gap-x-3 gap-y-10 pb-24">
              {tenis.map((item) => (
                <div
                  key={item.id}
                  className="bg-[#EBE9EA] w-[100%] min-h-[300px] flex place-content-center place-items-center"
                >
                  <img src={item.src} />
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>

      <footer className="bg-[#181818] text-white flex place-items-center place-content-center font-normal">
        {' '}
        <p className="text-lg py-4">Todos os direitos reservados.</p>
      </footer>
    </>
  );
}
